services:
  db:
    image: 'postgres:15-alpine'
    environment:
      POSTGRES_USER: hyper
      POSTGRES_PASSWORD: kitten
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    depends_on:
      - 'db'
      - 'cssbundler'
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - '..:/app'

  cssbundler:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
    command: yarn build:css --watch
    volumes:
      - '..:/app'

volumes:
  pgdata:
